version: "3"

services:

  # frontend:
  #   image: h5game_platform-frontend:v2.0
  #   build:
  #     context: ./site
  #     dockerfile: Dockerfile  # 文件名标准化
  #     args:
  #       NEXT_PUBLIC_FRONT_URL: "${PUBLIC_FRONT_URL}"
  #       BUILD_ENV: "production"
  #   ports:
  #     - "${FRONT_PORT}:3000"
  #   networks:
  #     - h5game_platform_net

  minio:
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z-cpuv1
    container_name: h5game_platform_minio
    ports:
      - "${MINIO_PORT}:9000"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - h5game_platform_net

volumes:
  minio_data:

networks:
  h5game_platform_net:
    driver: bridge