version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z-cpuv1
    container_name: h5game_platform_minio
    ports:
      - "9000:9000"
      - "9001:9001"  # Console port when debug
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data: