# docker/Dockerfile
FROM python:3.9-slim

# 设置工作目录
WORKDIR /backend

# 安装依赖
COPY requirements.txt .
RUN true
RUN pip install --no-cache-dir -r requirements.txt

# 复制应用代码
COPY . .
RUN true

# 启动应用
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8848", \
     "--log-level", "warning", "--no-access-log"]
