CREATE TABLE "game_list" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"title" VARCHAR(255),
	"description" TEXT,
	"release_date" DATE,
	"download_url" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE "tag" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE "picture" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"url" VARCHAR(255),
	"type" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE "developer" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE "online" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"length" INTEGER,
	"height" INTEGER,
	"url" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE "game_list_tags" (
    "game_id" INTEGER NOT NULL,
    "tag_id" INTEGER NOT NULL,
    PRIMARY KEY("game_id", "tag_id"),
    FOREIGN KEY("game_id") REFERENCES "game_list"("id") ON DELETE CASCADE,
    FOREIGN KEY("tag_id") REFERENCES "tag"("id") ON DELETE CASCADE
);

CREATE TABLE "game_list_pictures" (
    "game_id" INTEGER NOT NULL,
    "picture_id" INTEGER NOT NULL,
    PRIMARY KEY("game_id", "picture_id"),
    FOREIGN KEY("game_id") REFERENCES "game_list"("id") ON DELETE CASCADE,
    FOREIGN KEY("picture_id") REFERENCES "picture"("id") ON DELETE CASCADE
);

CREATE TABLE "game_list_developers" (
    "game_id" INTEGER NOT NULL,
    "developer_id" INTEGER NOT NULL,
    PRIMARY KEY("game_id", "developer_id"),
    FOREIGN KEY("game_id") REFERENCES "game_list"("id") ON DELETE CASCADE,
    FOREIGN KEY("developer_id") REFERENCES "developer"("id") ON DELETE CASCADE
);

CREATE TABLE "game_list_online" (
    "game_id" INTEGER NOT NULL,
    "online_id" INTEGER NOT NULL,
    PRIMARY KEY("game_id", "online_id"),
    FOREIGN KEY("game_id") REFERENCES "game_list"("id") ON DELETE CASCADE,
    FOREIGN KEY("online_id") REFERENCES "online"("id") ON DELETE CASCADE
);